# Generated by Django 3.2.6 on 2021-09-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='nationality',
            field=models.CharField(choices=[('Rwandan', 'Rwandan'), ('Kenyan', 'Kenyan'), ('Ugandan', 'Ugandan'), ('SouthSudanes', 'SouthSudanes'), ('Sudanes', 'Sudanes')], max_length=15),
        ),
    ]
